content:
  - name: news
    label: News
    path: content/news
    type: collection

  - name: academicos
    label: Académicos
    path: content/academicos
    type: collection
    filename: _index.md

    fields:
      - name: title
        label: Nombre
        type: text
        required: true

      - name: role
        label: Cargo
        type: text

      - name: degree
        label: Grado
        type: text

      - name: email
        label: Email
        type: text

      - name: summary
        label: Resumen
        type: text

      - name: topics
        label: Áreas
        type: list

      - name: body
        label: Contenido
        type: rich-text