# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Quiénes somos
    url: quienes-somos/
    weight: 10

  - name: Académicos
    url: academicos/
    weight: 20

  - name: Labs
    url: laboratorios/
    weight: 30

  - name: Temas
    url: temas/
    weight: 40

  - name: Noticias
    url: blog/
    weight: 50


  - name: Eventos
    url: eventos/
    weight: 60

  - name: Formación
    url: formacion/
    weight: 70

  - name: Contacto
    url: contacto/
    weight: 80
