media:
  input: static/uploads
  output: /uploads

content:
   # Noticias #
  - name: news
    label: News
    type: collection
    path: content/blog
    filename: "{year}-{month}-{day}-{primary}.md"
    format: yaml-frontmatter
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: summary, label: Summary, type: text }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }

  # Académicos #
  - name: academicos
    label: Académicos
    type: collection
    path: content/academicos
    filename: "{primary}/_index.md"
    format: yaml-frontmatter

    fields:
      - { name: title, label: Nombre, type: string }
      - { name: role, label: Cargo, type: string }
      - { name: degree, label: Grado, type: string }
      - { name: email, label: Email, type: string }
      - { name: topics, label: Áreas, type: list }
      - { name: image, label: Foto, type: image }
      - { name: body, label: Contenido, type: rich-text }

  # Laboratorios #
  - name: laboratorios
    label: Laboratorios
    type: collection
    path: content/laboratorios
    filename: "{primary}/_index.md"

    fields:
      - { name: title, label: Nombre, type: string }
      - { name: summary, label: Descripción, type: text }
      - { name: image, label: Imagen, type: image }
      - { name: body, label: Contenido, type: rich-text }

  # Eventos #
  - name: eventos
    label: Eventos
    type: collection
    path: content/eventos
    filename: "{year}-{month}-{day}-{primary}.md"

    fields:
      - { name: title, label: Título, type: string }
      - { name: date, label: Fecha, type: date }
      - { name: summary, label: Resumen, type: text }
      - { name: image, label: Imagen, type: image }
      - { name: body, label: Contenido, type: rich-text }

  # Quienes somos #
  - name: quienes
    label: Quiénes somos
    type: file
    path: content/quienes/_index.md
    fields:
      - { name: title, label: Título, type: string }
      - { name: body, label: Contenido, type: rich-text }

  # Formación #
  - name: formacion
    label: Formación
    type: file
    path: content/formacion/_index.md
    fields:
      - { name: title, label: Título, type: string }
      - { name: body, label: Contenido, type: rich-text }

  # Contacto #
  - name: contacto
    label: Contacto
    type: file
    path: content/contacto/_index.md
    fields:
      - { name: title, label: Título, type: string }
      - { name: body, label: Contenido, type: rich-text }